package com.puyixiaowo.tnews.manager.domain;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.id
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.menu_name
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.icon
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.sort
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private Long sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.href
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.status
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.remark
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.type
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.code
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.pid
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_menu.is_expand
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private Integer isExpand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager_menu
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.id
     *
     * @return the value of manager_menu.id
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.id
     *
     * @param id the value for manager_menu.id
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.menu_name
     *
     * @return the value of manager_menu.menu_name
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.menu_name
     *
     * @param menuName the value for manager_menu.menu_name
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.icon
     *
     * @return the value of manager_menu.icon
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.icon
     *
     * @param icon the value for manager_menu.icon
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.sort
     *
     * @return the value of manager_menu.sort
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.sort
     *
     * @param sort the value for manager_menu.sort
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.href
     *
     * @return the value of manager_menu.href
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.href
     *
     * @param href the value for manager_menu.href
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.status
     *
     * @return the value of manager_menu.status
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.status
     *
     * @param status the value for manager_menu.status
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.remark
     *
     * @return the value of manager_menu.remark
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.remark
     *
     * @param remark the value for manager_menu.remark
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.type
     *
     * @return the value of manager_menu.type
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.type
     *
     * @param type the value for manager_menu.type
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.code
     *
     * @return the value of manager_menu.code
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.code
     *
     * @param code the value for manager_menu.code
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.pid
     *
     * @return the value of manager_menu.pid
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.pid
     *
     * @param pid the value for manager_menu.pid
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_menu.is_expand
     *
     * @return the value of manager_menu.is_expand
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public Integer getIsExpand() {
        return isExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_menu.is_expand
     *
     * @param isExpand the value for manager_menu.is_expand
     *
     * @mbg.generated Sun Jan 15 23:21:58 CST 2017
     */
    public void setIsExpand(Integer isExpand) {
        this.isExpand = isExpand;
    }
}