package com.puyixiaowo.tnews.manager.domain;

import java.io.Serializable;

public class Permission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_permission.id
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_permission.menu_id
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_permission.permission_name
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_permission.permission
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager_permission
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_permission.id
     *
     * @return the value of manager_permission.id
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_permission.id
     *
     * @param id the value for manager_permission.id
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_permission.menu_id
     *
     * @return the value of manager_permission.menu_id
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_permission.menu_id
     *
     * @param menuId the value for manager_permission.menu_id
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_permission.permission_name
     *
     * @return the value of manager_permission.permission_name
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_permission.permission_name
     *
     * @param permissionName the value for manager_permission.permission_name
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_permission.permission
     *
     * @return the value of manager_permission.permission
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_permission.permission
     *
     * @param permission the value for manager_permission.permission
     *
     * @mbg.generated Sun Jan 08 22:36:57 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }
}