package com.puyixiaowo.tnews.manager.domain;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.id
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.loginname
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.nickname
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.password
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.create_time
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.last_login_time
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.status
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager_user
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.id
     *
     * @return the value of manager_user.id
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.id
     *
     * @param id the value for manager_user.id
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.loginname
     *
     * @return the value of manager_user.loginname
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.loginname
     *
     * @param loginname the value for manager_user.loginname
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.nickname
     *
     * @return the value of manager_user.nickname
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.nickname
     *
     * @param nickname the value for manager_user.nickname
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.password
     *
     * @return the value of manager_user.password
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.password
     *
     * @param password the value for manager_user.password
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.create_time
     *
     * @return the value of manager_user.create_time
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.create_time
     *
     * @param createTime the value for manager_user.create_time
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.last_login_time
     *
     * @return the value of manager_user.last_login_time
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.last_login_time
     *
     * @param lastLoginTime the value for manager_user.last_login_time
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.status
     *
     * @return the value of manager_user.status
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.status
     *
     * @param status the value for manager_user.status
     *
     * @mbg.generated Mon Jan 16 14:21:39 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}