package com.puyixiaowo.tnews.member.domain;

import java.io.Serializable;
import java.util.Date;

public class MemberFavorite implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_favorite.id
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_favorite.member_id
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_favorite.type
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_favorite.favorite_id
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    private Long favoriteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_favorite.create_time
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_member_favorite
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_favorite.id
     *
     * @return the value of t_member_favorite.id
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_favorite.id
     *
     * @param id the value for t_member_favorite.id
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_favorite.member_id
     *
     * @return the value of t_member_favorite.member_id
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_favorite.member_id
     *
     * @param memberId the value for t_member_favorite.member_id
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_favorite.type
     *
     * @return the value of t_member_favorite.type
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_favorite.type
     *
     * @param type the value for t_member_favorite.type
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_favorite.favorite_id
     *
     * @return the value of t_member_favorite.favorite_id
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public Long getFavoriteId() {
        return favoriteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_favorite.favorite_id
     *
     * @param favoriteId the value for t_member_favorite.favorite_id
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public void setFavoriteId(Long favoriteId) {
        this.favoriteId = favoriteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_favorite.create_time
     *
     * @return the value of t_member_favorite.create_time
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_favorite.create_time
     *
     * @param createTime the value for t_member_favorite.create_time
     *
     * @mbg.generated Sun Mar 05 20:23:57 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}