package com.puyixiaowo.tnews.news.domain;

import java.io.Serializable;
import java.util.Date;

public class News implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.nid
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String nid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.title
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.content
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.content_with_imgs
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String contentWithImgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.source
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.html
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String html;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.face_url
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String faceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.description
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.news_channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private Long newsChannelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.channel_name
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.link
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.imageurls
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String imageurls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.pub_date
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private Date pubDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.create_time
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.creator_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.status
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.face_url_keys
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String faceUrlKeys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.all_list
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private String allList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_news
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.id
     *
     * @return the value of t_news.id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.id
     *
     * @param id the value for t_news.id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.nid
     *
     * @return the value of t_news.nid
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.nid
     *
     * @param nid the value for t_news.nid
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setNid(String nid) {
        this.nid = nid == null ? null : nid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.title
     *
     * @return the value of t_news.title
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.title
     *
     * @param title the value for t_news.title
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.content
     *
     * @return the value of t_news.content
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.content
     *
     * @param content the value for t_news.content
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.content_with_imgs
     *
     * @return the value of t_news.content_with_imgs
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getContentWithImgs() {
        return contentWithImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.content_with_imgs
     *
     * @param contentWithImgs the value for t_news.content_with_imgs
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setContentWithImgs(String contentWithImgs) {
        this.contentWithImgs = contentWithImgs == null ? null : contentWithImgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.source
     *
     * @return the value of t_news.source
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.source
     *
     * @param source the value for t_news.source
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.html
     *
     * @return the value of t_news.html
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.html
     *
     * @param html the value for t_news.html
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.face_url
     *
     * @return the value of t_news.face_url
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getFaceUrl() {
        return faceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.face_url
     *
     * @param faceUrl the value for t_news.face_url
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setFaceUrl(String faceUrl) {
        this.faceUrl = faceUrl == null ? null : faceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.description
     *
     * @return the value of t_news.description
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.description
     *
     * @param description the value for t_news.description
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.channel_id
     *
     * @return the value of t_news.channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.channel_id
     *
     * @param channelId the value for t_news.channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.news_channel_id
     *
     * @return the value of t_news.news_channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public Long getNewsChannelId() {
        return newsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.news_channel_id
     *
     * @param newsChannelId the value for t_news.news_channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setNewsChannelId(Long newsChannelId) {
        this.newsChannelId = newsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.channel_name
     *
     * @return the value of t_news.channel_name
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.channel_name
     *
     * @param channelName the value for t_news.channel_name
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.link
     *
     * @return the value of t_news.link
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.link
     *
     * @param link the value for t_news.link
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.imageurls
     *
     * @return the value of t_news.imageurls
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getImageurls() {
        return imageurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.imageurls
     *
     * @param imageurls the value for t_news.imageurls
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setImageurls(String imageurls) {
        this.imageurls = imageurls == null ? null : imageurls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.pub_date
     *
     * @return the value of t_news.pub_date
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.pub_date
     *
     * @param pubDate the value for t_news.pub_date
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.create_time
     *
     * @return the value of t_news.create_time
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.create_time
     *
     * @param createTime the value for t_news.create_time
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.creator_id
     *
     * @return the value of t_news.creator_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.creator_id
     *
     * @param creatorId the value for t_news.creator_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.status
     *
     * @return the value of t_news.status
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.status
     *
     * @param status the value for t_news.status
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.face_url_keys
     *
     * @return the value of t_news.face_url_keys
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getFaceUrlKeys() {
        return faceUrlKeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.face_url_keys
     *
     * @param faceUrlKeys the value for t_news.face_url_keys
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setFaceUrlKeys(String faceUrlKeys) {
        this.faceUrlKeys = faceUrlKeys == null ? null : faceUrlKeys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.all_list
     *
     * @return the value of t_news.all_list
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public String getAllList() {
        return allList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.all_list
     *
     * @param allList the value for t_news.all_list
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setAllList(String allList) {
        this.allList = allList == null ? null : allList.trim();
    }
}