package com.puyixiaowo.tnews.news.domain;

import java.io.Serializable;

public class NewsApiChannel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_api_channel.id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_api_channel.api_channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private Long apiChannelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_api_channel.news_channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private Long newsChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_news_api_channel
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_api_channel.id
     *
     * @return the value of t_news_api_channel.id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_api_channel.id
     *
     * @param id the value for t_news_api_channel.id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_api_channel.api_channel_id
     *
     * @return the value of t_news_api_channel.api_channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public Long getApiChannelId() {
        return apiChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_api_channel.api_channel_id
     *
     * @param apiChannelId the value for t_news_api_channel.api_channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setApiChannelId(Long apiChannelId) {
        this.apiChannelId = apiChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_api_channel.news_channel_id
     *
     * @return the value of t_news_api_channel.news_channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public Long getNewsChannelId() {
        return newsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_api_channel.news_channel_id
     *
     * @param newsChannelId the value for t_news_api_channel.news_channel_id
     *
     * @mbg.generated Thu Feb 09 10:39:56 CST 2017
     */
    public void setNewsChannelId(Long newsChannelId) {
        this.newsChannelId = newsChannelId;
    }
}